name: Automated Data Preprocessing CI

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Mohammed-Noeno-Hadianto.py \
            --input "namadataset_raw/netflix_titles.csv" \
            --output "namadataset_preprocessing/netflix_preprocessed.csv"
            
      - name: Upload preprocessed dataset as artifact
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-dataset
          
          path: namadataset_preprocessing/netflix_preprocessed.csv
