# Nama workflow Anda
name: Automated Data Preprocessing CI

# Trigger: Kapan workflow ini akan berjalan
on:
  # Berjalan setiap kali ada 'push' ke branch 'main'
  push:
    branches: [ "main" ]
  
  # Memungkinkan Anda menjalankan workflow ini secara manual dari tab Actions
  workflow_dispatch:

# Daftar pekerjaan (jobs) yang akan dieksekusi
jobs:
  # Kita hanya punya satu job: 'preprocess'
  preprocess:
    # Menggunakan OS Ubuntu versi terbaru
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dijalankan
    steps:
      # 1. Mengunduh (checkout) kode repository Anda ke server GitHub
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Menyiapkan environment Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Anda bisa ganti versi Python jika perlu

      # 3. Meng-install dependencies dari file requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Menjalankan script preprocessing Anda
      - name: Run preprocessing script
        run: |
          # Pastikan path input dan output ini sesuai dengan struktur repo Anda
          python preprocessing/automate_Nama-siswa.py \
            --input "namadataset_raw/netflix_titles.csv" \
            --output "namadataset_preprocessing/netflix_preprocessed.csv"
            
      # 5. Mengunggah hasil preprocessing sebagai artefak
      - name: Upload preprocessed dataset as artifact
        uses: actions/upload-artifact@v4
        with:
          # Nama artefak yang akan muncul di halaman GitHub Actions
          name: preprocessed-dataset
          
          # Path ke file yang ingin Anda unggah
          path: namadataset_preprocessing/netflix_preprocessed.csv
